// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjEvaOF6L2dETOWsfK6FbSq33jVmOWQ60',
    appId: '1:618152078949:web:482529c3e259a3b38c208c',
    messagingSenderId: '618152078949',
    projectId: 'sinavotomasyon-6bc04',
    authDomain: 'sinavotomasyon-6bc04.firebaseapp.com',
    storageBucket: 'sinavotomasyon-6bc04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIFX8JwYLrOs0YoQ7bV5jT0hDXxWcH1mc',
    appId: '1:618152078949:android:6ccc6caa77552b718c208c',
    messagingSenderId: '618152078949',
    projectId: 'sinavotomasyon-6bc04',
    storageBucket: 'sinavotomasyon-6bc04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIhLieHyJqc18dDktNobXN8s_QIE-P4sE',
    appId: '1:618152078949:ios:04fd37d921ef137c8c208c',
    messagingSenderId: '618152078949',
    projectId: 'sinavotomasyon-6bc04',
    storageBucket: 'sinavotomasyon-6bc04.appspot.com',
    iosBundleId: 'com.example.flutterdenemeler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIhLieHyJqc18dDktNobXN8s_QIE-P4sE',
    appId: '1:618152078949:ios:04fd37d921ef137c8c208c',
    messagingSenderId: '618152078949',
    projectId: 'sinavotomasyon-6bc04',
    storageBucket: 'sinavotomasyon-6bc04.appspot.com',
    iosBundleId: 'com.example.flutterdenemeler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjEvaOF6L2dETOWsfK6FbSq33jVmOWQ60',
    appId: '1:618152078949:web:6b51cb51c599aba48c208c',
    messagingSenderId: '618152078949',
    projectId: 'sinavotomasyon-6bc04',
    authDomain: 'sinavotomasyon-6bc04.firebaseapp.com',
    storageBucket: 'sinavotomasyon-6bc04.appspot.com',
  );
}
